# Generated by Django 3.0.5 on 2021-05-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_predict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100000000000)),
                ('img_predict', models.CharField(max_length=100000000000)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
